-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 17, 2022 at 02:48 AM
-- Server version: 10.4.19-MariaDB
-- PHP Version: 8.0.7

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sample_penjualan`
--

-- --------------------------------------------------------

--
-- Table structure for table `listproduk`
--

CREATE TABLE `listproduk` (
  `id_produk` int(4) NOT NULL DEFAULT 0,
  `nama` varchar(300) NOT NULL,
  `merk` varchar(50) NOT NULL,
  `harga` int(8) NOT NULL,
  `ukuran` int(6) NOT NULL,
  `satuan_ukuran` varchar(20) NOT NULL,
  `satuan_barang` varchar(20) NOT NULL,
  `jenis` varchar(50) DEFAULT NULL,
  `deskripsi` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `listproduk`
--

INSERT INTO `listproduk` (`id_produk`, `nama`, `merk`, `harga`, `ukuran`, `satuan_ukuran`, `satuan_barang`, `jenis`, `deskripsi`) VALUES
(1, 'BETADINE GARGLE 190 ML', 'Betadine', 32000, 190, 'ml', 'Botol', 'Obat Kumur', '<p>asdas23234dasd</p>\r\n'),
(2, 'BETADINE GARGLE 100 ML', 'Betadine', 17000, 100, 'ml', 'Botol', 'Obat Kumur', 'Obat kumur antiseptik untuk rongga mulut seperti gigi berlubang, gusi bengkak, sakit tenggorokan, sariawan, bau mulut dan nafas tak segar'),
(3, 'BETADINE OINT 20 GR', 'Betadine', 30000, 20, 'gr', 'Tube', 'Obat Keras', 'Salep luka yang dapat digunakan untuk luka terbuka maupun luka bakar.'),
(12, 'Kid Zee Chocolate 350g', 'ZEE', 44000, 350, 'gr', 'kotak', 'susu', '<p>Kid Zee Chocolate merupakan susu untuk anak dengan rasa coklat yang diproduksi oleh PT. Kalbe Farma. Kid Zee Chocolate mengandung omega 3:6, kolin, prebiotik dan tinggi kalsium. Kolin memiliki peran membentuk fosfatidilkolin yang berperan penting bagi membran sel, prebiotik mempertahankan fungsi pada saluran cerna, serta kalsium yang tinggi berperan dalam peembentukan tulang dan kepadatan tulang dan gigi.<br />\r\nIndikasi / Manfaat / Kegunaan :<br />\r\nmemberikan nutrisi untuk anak dan membantu memadatkan tulang dan gigi<br />\r\nDosis<br />\r\n2 gelas per hari<br />\r\nPerhatian<br />\r\ntidak cocok untuk anak dibawah 1 tahun. jangan simpan pada lemari pendingin.</p>\r\n'),
(13, 'DECOLGEN 4 tab', 'Decolgen', 3000, 3, 'gr', 'tablet', 'Obat Bebas Terbatas', '<p>Decolgen merupakan obat untuk meringankan gejala flu seperti demam, sakit kepala, hidung tersumbat dan bersin-bersin.</p>\r\n\r\n<p>Setiap 1 tablet Decolgen mengandung:</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; Paracetamol (Acetaminophen) adalah zat aktif yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bisa diperoleh tanpa resep dokter.</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; Chlorpheniramine maleate (CTM) adalah zat aktif yang digunakan untuk mengobati &nbsp;gejala alergi seperti rhinitis dan urtikaria. Termasuk dalam golongan antihistamin generasi pertama yang memiliki efek sedatif rendah.</p>\r\n\r\n<p>&nbsp; &nbsp; &nbsp; Phenylpropalamine HCl adalah zat aktif yang berfungsi sebagai stimulan dan nasal dekongestan (untuk mengatasi pilek dan hidung tersumbat).<br />\r\nIndikasi / Manfaat / Kegunaan :<br />\r\nmeredakan gejala flu : sakit kepala, demam, bersin-bersin dan hidung tersumbat<br />\r\nSub Kategori<br />\r\nObat Batuk dan Pilek<br />\r\nTag<br />\r\nflu , influenza , demam , sakit kepala , hidung tersumbat , bersin-bersin<br />\r\nKomposisi<br />\r\nparasetamol 400 mg, fenilpropanolamin 12.5 mg, ctm 1 mg<br />\r\nDosis<br />\r\n3 x 1 tablet<br />\r\nPenyajian<br />\r\nsesudah makan<br />\r\nCara Penyimpanan<br />\r\nsimpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung<br />\r\nPerhatian<br />\r\nhipersensitivitas komponen, penderita hipertensi, gangguan jantung dan diabetes melitus, gangguan fungsi hati berat<br />\r\nEfek Samping<br />\r\nmengantuk, ganguan pencernaan, insomnia, gelisah, eksitasi,tremor, takikardi,aritmia, mulut kering, sulit berkemih, penggunaan dosis besar dan jangka panjang menyebabkan kerusakan hati.<br />\r\nKemasan<br />\r\n1 Dos isi 25 Strip<br />\r\nNama Standar MIMS<br />\r\nDECOLGEN TAB STR 4&#39;S<br />\r\nGolongan Obat<br />\r\nobat bebas terbatas Obat Bebas Terbatas</p>\r\n'),
(14, 'Bebelac 3 vanilla 400g', 'Bebelac', 65000, 400, 'gr', 'kotak', 'susu', '<p>&bull; SUSU PERTUMBUHAN BEBELAC 3: dengan minyak ikan dan omega 6 lebih tinggi</p>\r\n\r\n<p>&bull; BARU LEBIH LEZAT: dengan berbagai pilihan rasa yang lezat</p>\r\n\r\n<p>&bull; NUTRISI PENTING: Minyak ikan, Omega 3, Omega 6, FOS:GOS 1:9, 13 Vitamin &amp; 9 Mineral</p>\r\n\r\n<p>&bull; SUSU PERTUMBUHAN ANAK: Usia 1-3 tahun&nbsp;</p>\r\n\r\n<p>Indikasi / Manfaat / Kegunaan :<br />\r\nSUSU PERTUMBUHAN ANAK: Usia 1-3 tahun &nbsp;<br />\r\nSub Kategori<br />\r\nProduk Nutrisi Bayi<br />\r\nTag<br />\r\nsusu<br />\r\nKomposisi<br />\r\nMinyak ikan, Omega 3, Omega 6 Bebelac dibuat dengan minyak ikan (0.26%) dan mengandung Asam a-linolenat (Omega 3) 107 mg/saji dan Asam linoleat (Omega 6) 1205 mg/saji. -FOS:GOS 1:9 -13 Vitamin &amp; 9 Mineral Dengan kandungan Zat Besi, Zinc, Iodium, Vitamin A, dan Kalsium untuk pertumbuhan yang optimal.</p>\r\n\r\n<p>&nbsp;<br />\r\nPenyajian<br />\r\nJumlah per Sajian :</p>\r\n\r\n<p>Takaran saji: 3 sendok takar(39g/235 ml)</p>\r\n\r\n<p>Standar pengenceran:&nbsp;</p>\r\n\r\n<p>235 ml Bebelac 3</p>\r\n\r\n<p>=200 ml air hangat + 3 sendok takar</p>\r\n\r\n<p>1 sendok takar = 13 g</p>\r\n\r\n<p>&nbsp;<br />\r\nPerhatian<br />\r\nTidak cocok untuk bayi dibawah usia 12 Bulan.</p>\r\n'),
(15, 'Anlene gold plus vanilla 175 g', 'Anlene', 35000, 175, 'gr', 'kotak', 'Obat bebas', '<p>Produk Nutrisi Parenteral</p>\r\n\r\n<p>Kemasan<br />\r\n1 Pcs<br />\r\nNama Standar&nbsp;<br />\r\nANLENE GOLD PLUS VANILA 175G BOX<br />\r\n<br />\r\nPabrik<br />\r\nFonterra<br />\r\n<br />\r\nGolongan Obat<br />\r\nobat bebas Obat Bebas</p>\r\n'),
(16, 'Dancow 5+ coklat 800g', 'Dancow', 86000, 800, 'gr', 'kotak', 'Obat bebas', '<p>DANCOW Advanced Excelnutri+ 5+ adalah susu untuk anak usia 5-12 tahun yang merupakan inovasi terbaru dari Nestle Research Centre. Dengan kandungan lebih dari 3X Lactobacillus rhamnosus di bandingkan produk sebelumnya.</p>\r\n\r\n<p>Produk Nutrisi /Enteral</p>\r\n\r\n<p>Kemasan<br />\r\n1 Dos<br />\r\nNama Standar MIMS<br />\r\nDANCOW 5+ COKLAT 800G</p>\r\n'),
(17, 'Diabetasol vita digest van 185g', 'Diabetasol', 45000, 185, 'gr', 'kotak', 'susu', '<p>susu khusus untuk penderita diabetes<br />\r\nIndikasi / Manfaat / Kegunaan :<br />\r\nsusu untuk membantu mengatur kadar glukosa darah pada diabetisi bila disertai dengan konsumsi rendah gula dan gizi seimbang<br />\r\nSub Kategori<br />\r\nProduk Nutrisi /Enteral</p>\r\n\r\n<p>Komposisi<br />\r\nlemak, protein, karbohidrat, natrium, vitamin, asam folat, kalsium, besi, fosfor, magnesium, zinc, yodium<br />\r\nDosis<br />\r\ndiminum setiap hari<br />\r\nPenyajian<br />\r\n4 sendok takar dilarutkan dalam 200 ml air matang<br />\r\nKemasan<br />\r\n1 Pcs<br />\r\nNama Standar MIMS<br />\r\nDIABETASOL VITA DIGEST VAN 185G</p>\r\n'),
(18, 'Entrasol gold vanilla 175g', 'Entrasol', 35000, 175, 'gr', 'kotak', 'Obat bebas', '<p>Entrasol Gold merupakan susu yang diformulasikan untuk usia 51 tahun ke atas agar tetap sehat dan aktif.</p>\r\n\r\n<p>Indikasi / Manfaat / Kegunaan :<br />\r\nuntuk usia 51 tahun ke atas agar tetap sehat dan aktif.<br />\r\nSub Kategori<br />\r\nProduk Nutrisi /Enteral</p>\r\n\r\n<p>Komposisi<br />\r\nHi Calcium, omega 3&amp;6, vitamin, dan mineral<br />\r\nDosis<br />\r\nSesuai kebutuhan<br />\r\nPenyajian<br />\r\nSeperti pada penyajian susu biasa<br />\r\nCara Penyimpanan<br />\r\nsimpan di tempat yang sejuk dan kering, serta terlindung dari sinar matahari langsung<br />\r\nKemasan<br />\r\n1 Pcs</p>\r\n'),
(19, 'Lactogen 1 preboitik 180g', 'lactogen', 33000, 180, 'gr', 'kotak', 'susu', '<p><strong>LACTOGEN 1</strong>&nbsp;merupakan susu formula yang diformulasi khusus bagi bayi usia 0-6 bulan untuk membantu tahap awal pertumbuhan anak. Susu formula ini mengandung&nbsp;<strong>Probiotik</strong>, LA dan ALA, serta Zat Besi, dan diperkaya dengan 12 Vitamin dan 11 mineral serta kandungan protein.</p>\r\n\r\n<p>Produk Nutrisi Bayi</p>\r\n\r\n<p>Kemasan<br />\r\n1 Pcs<br />\r\nNama Standar MIMS<br />\r\nLACTOGEN 1 PREBOITIK G/F 180G</p>\r\n'),
(20, 'SGM ananda 0-6 bln 150g', 'SGM', 15000, 150, 'gr', 'kotak', 'susu', '<p>SGM ANANDA 0-6BLN 400G BOX merupakan susu formula yang digunakan untuk bayi usia 0 &ndash; 6 bulan untuk melengkapi nutrisi penting yang dibutuhkan, memiliki kandungan:<br />\r\nPadatan susu (protein whey, laktosa)<br />\r\nMinyak nabati (mengandung lesitin kedelai, antioksidan askorbil palmitat dan campuran tokoferol)<br />\r\nMaltodekstrin<br />\r\nSusu bubuk skim<br />\r\nFOS-inulin<br />\r\nPremiks vitamin dan mineral<br />\r\nAA (mengandung antioksidan tokoferol dan askorbil palmitat)&nbsp;<br />\r\nDHA (mengandung antioksidan tokoferol).</p>\r\n\r\n<p>Siapkan larutan hanya untuk satu kali pemberian dan diberikan langsung setelah disiapkan. Buang larutan yang tersisa setelah 2 jam. Penggunaan formula untuk bayi hanya atas rekomendasi Dokter. ASI adalah yang terbaik.&nbsp;</p>\r\n\r\n<p>Indikasi / Manfaat / Kegunaan :<br />\r\nSusu formula untuk bayi usia 0 &ndash; 6 bulan.&nbsp;<br />\r\nSub Kategori<br />\r\nProduk Nutrisi Bayi</p>\r\n\r\n<p>Komposisi<br />\r\nPadatan susu (protein whey, laktosa)<br />\r\nMinyak nabati (mengandung lesitin kedelai, antioksidan askorbil palmitat dan campuran tokoferol)<br />\r\nMaltodekstrin<br />\r\nSusu bubuk skim<br />\r\nFOS-inulin<br />\r\nPremiks vitamin dan mineral<br />\r\nAA (mengandung antioksidan tokoferol dan askorbil palmitat)<br />\r\nDHA (mengandung antioksidan tokoferol). &nbsp;<br />\r\nDosis<br />\r\nDisesuaikan dengan petunjuk dokter atau sesuai dengan kemasan produk susu.&nbsp;<br />\r\nPenyajian<br />\r\nSiapkan larutan hanya untuk satu kali pemberian dan diberikan langsung setelah disiapkan. Buang larutan yang tersisa setelah 2 jam&nbsp;<br />\r\nCara Penyimpanan<br />\r\nSetelah dibuka, lipat kantung sachet susu formula bayi beberapa kali. Simpan kantung sachet susu formula untuk bayi baru lahir dan sendok takar dalam wadah kering, bersih, sejuk dan tertutup rapat tidak lebih dari 1 (satu) bulan. Jangan diberikan pada bayi Anda, jika terjadi perubahan warna, bau, dan rasa dari bubuk susu. Susu yang bagus untuk bayi adalah susu yang tidak mengalami perubahan warna, bau, dan rasa dari bubuk susu. &nbsp;<br />\r\nPerhatian<br />\r\nPemakaian SGM ANANDA 0-6BLN 400G BOX atas nasehat Dokter.&nbsp;<br />\r\nPerhatian petunjuk penyiapan, penggunaan dan penyimpanan.&nbsp;<br />\r\nKemasan<br />\r\n1 Pcs</p>\r\n'),
(21, 'SGM eksplor 1 plus vanilla 150g', 'SGM', 15000, 150, 'gr', 'kotak', 'susu', '<p>SGM EKSPLOR 1 PLUS VANILLA 150G&nbsp;merupakan susu pertumbuhan untuk anak usia 1 - 3 tahun&nbsp;untuk melengkapi nutrisi penting yang dibutuhkan,&nbsp;agar si kecil dapat menjadi anak generasi maju yang supel, kreatif dan mandiri.&nbsp;</p>\r\n\r\n<p>SGM EKSPLOR 1 PLUS VANILLA 150G&nbsp;&nbsp;memiliki kandungan:&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Minyak Ikan, Omega 3, Omega 6, zat Besi untuk mendukung daya pikir si Kecil</li>\r\n	<li>Tinggi Protein yang penting untuk mendukung pertumbuhan &amp; perkembangan si Kecil</li>\r\n	<li>Kalsium &amp; Vitamin D untuk mendukung pembentukan &amp; mempertahankan kepadatan tulang &amp; gigi si Kecil</li>\r\n	<li>Vitamin C &amp; Zinc untuk mendukung daya tahan tubuh si Kecil</li>\r\n	<li>Serat Pangan Inulin untuk mempertahankan kesehatan saluran cerna si Kecil</li>\r\n	<li>11 Vitamin &amp; 8 mineral lainnya untuk dukung tumbuh kembang optimal si Kecil</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Dukung si Kecil untuk dapat memiliki 5 potensi prestasi anak generasi maju :&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Berpikir Kreatif</li>\r\n	<li>Bantu Tumbuh Kembang</li>\r\n	<li>Supel, Mandiri</li>\r\n	<li>Percaya Diri</li>\r\n</ul>\r\n\r\n<p><br />\r\nMohon memperhatikan petunjuk penyiapan susu SGM Eksplor 1 Plus yang tertera pada kemasan.&nbsp;</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Susu Pertumbuhan untuk Anak Usia 1-3 Tahun.&nbsp;&nbsp;</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<ul>\r\n	<li>Minyak Ikan, Omega 3, Omega 6, zat Besi untuk mendukung daya pikir si Kecil</li>\r\n	<li>Tinggi Protein yang penting untuk mendukung pertumbuhan &amp; perkembangan si Kecil</li>\r\n	<li>Kalsium &amp; Vitamin D untuk mendukung pembentukan &amp; mempertahankan kepadatan tulang &amp; gigi si Kecil</li>\r\n	<li>Vitamin C &amp; Zinc untuk mendukung daya tahan tubuh si Kecil</li>\r\n	<li>Serat Pangan Inulin untuk mempertahankan kesehatan saluran cerna si Kecil</li>\r\n	<li>11 Vitamin &amp; 8 mineral lainnya untuk dukung tumbuh kembang optimal si Kecil&nbsp;</li>\r\n</ul>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Berikan SGM Eksplor 1 Plus minimal tiga kali sehari untuk bantu lengkapi nutrisi si Kecil.&nbsp;</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Mohon memperhatikan petunjuk penyiapan susu SGM Eksplor 1 Plus yang tertera pada kemasan.&nbsp;</p>\r\n'),
(22, 'SGM eksplor 1 plus madu150g', 'SGM', 15000, 150, 'gr', 'kotak', 'susu', '<p>SGM EKSPLOR 1 PLUS MADU 150G&nbsp;merupakan susu pertumbuhan untuk anak usia 1 - 3 tahun&nbsp;untuk melengkapi nutrisi penting yang dibutuhkan,&nbsp;agar si kecil dapat menjadi anak generasi maju yang supel, kreatif dan mandiri.&nbsp;</p>\r\n\r\n<p>SGM EKSPLOR 1 PLUS MADU 150G&nbsp;memiliki kandungan:&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Minyak Ikan, Omega 3, Omega 6, zat Besi untuk mendukung daya pikir si Kecil</li>\r\n	<li>Tinggi Protein yang penting untuk mendukung pertumbuhan &amp; perkembangan si Kecil</li>\r\n	<li>Kalsium &amp; Vitamin D untuk mendukung pembentukan &amp; mempertahankan kepadatan tulang &amp; gigi si Kecil</li>\r\n	<li>Vitamin C &amp; Zinc untuk mendukung daya tahan tubuh si Kecil</li>\r\n	<li>Serat Pangan Inulin untuk mempertahankan kesehatan saluran cerna si Kecil</li>\r\n	<li>11 Vitamin &amp; 8 mineral lainnya untuk dukung tumbuh kembang optimal si Kecil&nbsp;</li>\r\n</ul>\r\n\r\n<p>Dukung si Kecil untuk dapat memiliki 5 potensi prestasi anak generasi maju :&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Berpikir Kreatif</li>\r\n	<li>Bantu Tumbuh Kembang</li>\r\n	<li>Supel</li>\r\n	<li>Mandiri</li>\r\n	<li>Percaya Diri&nbsp;</li>\r\n</ul>\r\n\r\n<p>Mohon memperhatikan petunjuk penyiapan susu SGM Eksplor 1 Plus yang tertera pada kemasan.&nbsp;&nbsp;</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Susu Pertumbuhan untuk Anak Usia 1-3 Tahun. &nbsp;</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Produk Nutrisi Bayi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<ul>\r\n	<li>Minyak Ikan, Omega 3, Omega 6, zat Besi untuk mendukung daya pikir si Kecil</li>\r\n	<li>Tinggi Protein yang penting untuk mendukung pertumbuhan &amp; perkembangan si Kecil</li>\r\n	<li>Kalsium &amp; Vitamin D untuk mendukung pembentukan &amp; mempertahankan kepadatan tulang &amp; gigi si Kecil</li>\r\n	<li>Vitamin C &amp; Zinc untuk mendukung daya tahan tubuh si Kecil</li>\r\n	<li>Serat Pangan Inulin untuk mempertahankan kesehatan saluran cerna si Kecil</li>\r\n	<li>11 Vitamin &amp; 8 mineral lainnya untuk dukung tumbuh kembang optimal si Kecil&nbsp;</li>\r\n</ul>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Berikan SGM Eksplor 1 Plus minimal tiga kali sehari untuk bantu lengkapi nutrisi si Kecil.&nbsp;</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Mohon memperhatikan petunjuk penyiapan susu SGM Eksplor 1 Plus yang tertera pada kemasan.&nbsp;&nbsp;</p>\r\n'),
(23, 'Lactogen 2 preboitik  180G', 'lactogen', 33000, 180, 'gr', 'kotak', 'susu', '<p>LACTOGEN 2 merupakan susu formula lanjutan yang diformulasi khusus bagi bayi usia 6-12 bulan untuk membantu tahap awal pertumbuhan anak.</p>\r\n\r\n<p>Indikasi Umum</p>\r\n\r\n<p>Susu Formula Bayi Usia 6 - 12 Bulan.</p>\r\n\r\n<p>Komposisi</p>\r\n\r\n<p>Padatan susu (susu bubuk skim, laktosa, bubuk whey), campuran minyak nabati (mengandung antioksidan tokoferol dan askorbil palmitat), maltodekstrin, 8 mineral dan premiks mineral, minyak LC-PUFA (mengandung minyak ikan (DHA), ARA, mengandung antioksidan tokoferol dan askorbil palmitat), pengemulsi lesitin kedelai, premiks vitamin, Lactobacillus reuteri DSM 17938</p>\r\n\r\n<p>Dosis</p>\r\n\r\n<p>Ikuti petunjuk penggunaan yang terdapat di kemasan.</p>\r\n\r\n<p>Aturan Pakai</p>\r\n\r\n<p>Cuci tangan Anda dengan sabun sebelum membersihkan dan mensterilkan peralatan minum bayi. 2. Cuci peralatan minum bayi dengan air yang mengalir sampai bersih. 3. Rebus peralatan minum bayi dalam air mendidih selama 5-10 menit. Biarkan dalam panci tertutup sampai saat akan dipakai. Bila peralatan minum bayi tidak langsung digunakan, harus disimpan di tempat yang bersih dan tertutup. 4. Cuci tangan dengan sabun dan air mengalir, kemudian keringkan sebelum mengambil peralatan minum bayi. 5. Rebus air minum sampai mendidih selama 10 menit, diamkan di dalam panci tertutup selama 10-15 menit sampai suhunya turun menjadi tidak kurang dari 70&deg;C. 6. Tuangkan air tersebut ke dalam peralatan minum bayi sesuai jumlah yang tertera pada &quot;Petunjuk Penggunaan&quot;. 7. Gunakan sendok takar yang tersedia di dalam kaleng. 8. Masukan bubuk Formula Bayi ke dalam peralatan minum bayi dengan jumlah takaran sesuai &quot;Petunjuk Penggunaan&quot;. 9. Kocok sampai bubuk Formula Bayi larut seluruhnya. 10. Dinginkan segera dengan merendam bagian bawah peralatan minum bayi di dalam air bersih dingin, sampai suhunya sesuai untuk diminum (Dicoba dengan meneteskan Formula Bayi pada pergelangan tangan, akan terasa agak hangat). 11. Sisa Formula Bayi yang sudah dilarutkan dibuang setelah 2 jam. 12. Tutup kaleng dengan rapat setelah digunakan dan simpan di tempat sejuk dan kering. Harus dihabiskan dalam waktu 3 minggu setelah dibuka.</p>\r\n\r\n<p>Perhatian</p>\r\n\r\n<p>Setiap penyajian hanya untuk sekali pemberian. Berikan sesegera mungkin dan ikuti petunjuk dengan tepat. Apabila tidak habis, buang sisa formula bayi yang ada dalam botol.</p>\r\n'),
(24, 'ANTIMO STR 10S', 'Antimo', 5000, 50, 'mg', 'strip', 'Obat Bebas Terbatas', '<p>Antimo merupakan obat yang digunakan untuk mengatasi rasa mual dan muntah akibat mabuk perjalanan (motion sickness) maupun kondisi vertigo. Antimo mengandung zat aktif Dimenhidrinat yaitu obat golongan antihistamin yang efektif untuk mual dan muntah yang disebabkan oleh banyak kondisi. Dimenhidrinat dibantu dengan Vitamin B6 akan bekerja secara efektif pada sistem saraf pusat dengan menghambat zat histamin dan mencegah adanya stimulasi di saraf otak dan telinga dalam yang bisa menyebabkan mual, muntah, dan pusing.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>mabuk, muntah dalam perjalanan yang di derita jika mempergunakan kendaraan bermotor kapal, kereta api atau pesawat udara</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Antivertigo</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>dimenhidrinat 50mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>&gt; 12 tahun: 1 tablet sehari (maksimal 8 tablet), anak 8-12 tahun: 1/2 tablet sehari (maksimal 3 tablet)</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>30 menit sebelum bepergian, jika perlu dapat diulang tiap 4 jam</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>gangguan hati, hipokalemia, hipersensitif terhadap antihistamin, retensi urin dan glaukoma</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>mengantuk, lesu, pusing, dan gangguan koordinasi terutama pada anak-anak, sakit kepala, gangguan psikomotor, mulut kering, pandangan kabur, retensi urin, susah buang air besar, peningkatan reflux lambung, mual, muntah, diare dan nyeri epigastrik, cardiac...</p>\r\n'),
(25, 'ANTIMO ANAK SYR RASA JERUK 5ML', 'Antimo', 15000, 12, 'mg', 'piece', 'Obat Bebas Terbatas', '<p>Antimo sirup merupakan anti mual atau muntah yang dikemas dalam bentuk sachet, dengan rasa strawberi yang disukai anak-anak dan praktis dibawa kemana-mana.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Beli Antimo Anak Syr Rasa Jeruk 5ML di apotek online K24klik dan dapatkan manfaatnya</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Mabuk, muntah dalam perjalanan yang diderita jika mempergunakan kendaraan bermotor, kapal, kereta api atau pesawat udara</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antiemetik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Dimenhidrinat 12mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Hiperemesis : Anak 2-6 tahun : 1-2 sachet setiap 6-8 jam jika perlu, tidak lebih dari sehari 150 mg.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Diminum &frac12; jam sebelum berpergian dan lebih baik setelah makan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Penderita gangguan hati, hipokalemia, hipersensitif terhadap antihistamin, retensi urin, glaukoma</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Depresi susunan saraf pusat seperti mengantuk, lesu pusing dan gangguan koordinasi (terutama pada anak-anak), sakit kepala, gangguan psikomotor, efek antimuskarinik seperti mulut kering, pandangan kabur, retensi urin, konstipasi dan peningkatan refluks lambung, gangguan saluran cerna seperti mual, muntah, diare dan nyeri epigastrik, aritmia jantung atau palpitasi</p>\r\n'),
(26, 'ANTIMO ANAK SYR STRAWBERY 5ML', 'Antimo', 15000, 12, 'mg', 'piece', 'Obat Bebas Terbatas', '<p>Antimo sirup merupakan anti mual atau muntah yang dikemas dalam bentuk sachet, dengan rasa strawberi yang disukai anak-anak dan praktis dibawa kemana-mana.</p>\r\n\r\n<p>Beli Antimo Anak Syr Strawbery 5ML di apotek online K24klik dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Mabuk, muntah dalam perjalanan yang diderita jika mempergunakan kendaraan bermotor, kapal, kereta api atau pesawat udara</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antiemetik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Dimenhidrinat 12,5mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Hiperemesis : Anak 2-6 tahun : 1-2 sachet setiap 6-8 jam jika perlu, tidak lebih dari sehari 150 mg.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Diminum &frac12; jam sebelum berpergian dan lebih baik setelah makan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Penderita gangguan hati, hipokalemia, hipersensitif terhadap antihistamin, retensi urin, glaukoma</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Depresi susunan saraf pusat seperti mengantuk, lesu pusing dan gangguan koordinasi (terutama pada anak-anak), sakit kepala, gangguan psikomotor, efek antimuskarinik seperti mulut kering, pandangan kabur, retensi urin, konstipasi dan peningkatan refluks lambung, gangguan saluran cerna seperti mual, muntah, diare dan nyeri epigastrik, aritmia jantung atau palpitasi</p>\r\n'),
(27, 'BODREX TAB', 'Bodrex', 5000, 650, 'mg', 'strip', 'Obat bebas', '<p>Paracetamol sendiri berfungsi sebagai anti nyeri dan penurun panas atau demam,paduan dengan Caffeine meningkatkan efek analgetik sehingga mampu meredakan nyeri ringan-sedang dengan cepat&nbsp;</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>meringankan sakit kepala, migren, demam, pusing</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Analgesik (Non Opiat) dan Antipiretik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Tiap tablet mengandung: Paracetamol 600 mg dan Caffeine 50 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>3-4 kali sehari 1-2 kaplet. Maksimal : 8 kaplet/24 jam. Tidak untuk anak</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Sesudah makan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Penderita dengan gangguan fungsi hati,Penderita yang hipersensitif terhadap salah satu atau seluruh komponen obat</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Dosis besar dapat menyebabkan kerusakan hati</p>\r\n'),
(28, 'BODREX FLU&BATUK BERDAHAK PE CAPL 4S', 'Bodrex', 2000, 568, 'mg', 'strip', 'Obat Kumur', '<p>Bodrex Flu &amp; Batuk Berdahak PE merupakan rangkaian dari bodrex flu &amp; batuk PE khusus untuk batuk berdahak pertama di Indonesia dengan PE (Phenylephrine) yang berfungsi sebagai dekongestan untuk meredakan hidung tersumbat. bodrex Flu &amp; Batuk PE berkhasiat atasi flu &amp; batuk tanpa ngantuk secara cepat dan aman.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat dan bersin-bersin yang disertai batuk berdahak.</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Analgesik (Non Opiat) dan Antipiretik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Tiap kaplet lapis dua mengandung : Paracetamol 500 mg, Phenylephrine HCL 10 mg, Glyceryl Guaiacolate 50 mg, Bromhexine HCL 8 mg.</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dewasa : 1 kaplet 3 kali sehari.</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Hati-hati penggunaan pada penderita dengan gangguan fungsi hati dan ginjal, glaukoma, hipertrofi prostat, hipertiroid dan retensi urin. Tidak dianjurkan penggunaan pada anak usia dibawah 2 tahun, wanita hamil dan menyusui, kecuali atas petunjuk dokter.</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Gangguan pencernaan, insomnia, gelisah, aksitasi, tremor, takikardia, mulit kering, palpitasi, dan retensi urin. Penggunaan dosis besar dan jangka panjang menyebabkan kerusakan hati.</p>\r\n'),
(29, 'BODREX FLU&BATUK KERING PE CAPL 4S', 'Bodrex', 2000, 582, 'mg', 'strip', 'Obat Bebas Terbatas', '<p>Bodrex Flu dan Batuk biru merupakan obat yang digunakan untuk mengatasi flu dan batuk tidak berdahak.</p>\r\n\r\n<p>Beli Bodrek Flu&amp;Batuk Kering STR 4&#39;S di apotek online K24klik dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Meredakan gejala-gejala flu yang disertai batuk kering</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Batuk dan Pilek</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Paracetamol 500 mg, pseudoephedrine HCl 30 mg, dextromethorphan HBr 12 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dewasa : 3 kali sehari 1 kaplet. Anak : 3 kali sehari &frac12; kaplet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Berikan bersama makanan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Gangguan fungsi hati dan ginjal, glaukoma, hipertrofi prostat, hipertiroid, penyakit jantung, DM. Dapat meningkatkan risiko gangguan fungsi hati pada pasien yang mengkonsumsi alkohol. Pasien dalam kondisi lemah fisik dan hipoksia. Hipertensi. Anak</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Gangguan psikomotorik, takikardi, aritmia, palpitasi, retensi urin; mengantuk. Kerusakan hati (karena dosis besar dan penggunaan jangka lama)</p>\r\n'),
(30, 'BODREX MIGRA TAB 4S', 'Bodrex', 2000, 580, 'mg', 'strip', 'Obat Bebas Terbatas', '<p>Membantu meringankan rasa sakit kepala pada migrain. Beli Bodrex Migra di K24klik dan dapatkan manfaatnya</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Meringankan rasa sakit kepala pada migrain.</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Analgesik (Non Opiat) dan Antipiretik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Paracetamol 350 mg, propyphenazone 150 mg, caffeine 50 mg.</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dewasa : 1 kaplet 3 kali sehari atau menurut petunjuk dokter</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Sebaiknya diberikan bersama makanan : Berikan sesudah makan.</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan di tempat sejuk dan kering serta terhindar dari sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Hati-hati penggunaan pada penderita porfiria. Hati-hati penggunaan obat ini pada penderita penyakit ginjal. Penggunaan obat ini pada penderita yang mengkonsumsi alkohol, dapat meningkatkan risiko kerusakan fungsi hati.Bila setelah 5 hari rasa nyeri tidak b</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>&ndash; Penggunaan jangka panjang dan dosis besar dapat menyebabkan kerusakan fungsi ginjal. &ndash; Reaksi hipersensitif.</p>\r\n'),
(31, 'KONIDIN TABLET 4S', 'Konidin', 3000, 125, 'mg', 'strip', 'Obat Bebas Terbatas', '<p>Tablet konidin sebagai obat batuk diproduksi oleh PT Konimex. Dalam 1 tablet konidin mengandung guaifenesin, dextromethorphan Hbr, dan CTM. Dextromethorphan HBr termasuk golongan antitusif jadi cocok untuk batuk kering. Guaifenesin merupakan ekspektoran yang dapat membantu melegakan tenggorokan, sehingga batuk akan lebih mudah dilepaskan. Terakhir, CTM sering kita dengar digunakan sebagai antihistamin untuk alerginya</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Untuk mengatasi batuk karena alergi, flu, pilek, atau sisa-sisa bronkitis</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Batuk dan Pilek</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Guaifenesin 100 mg, dextromethorphan HBr 5 mg, chlorpeniramine maleate 2 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>dewasa dan anak-anak &gt; 12 tahun: 3 x sehari 1-2 tablet; anak-anak 6-12 tahun: 3 x sehari 1/2-1 tablet; anak-anak 3-6 tahun: 3 x sehari 1/4-1/2 tablet;</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Diberikan setelah makan</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>mengantuk, letih, gangguan pencernaan</p>\r\n'),
(32, 'OSKADON TAB STR 4S', 'Oskadon', 2000, 535, 'mg', 'strip', 'Obat bebas', '<p>Oskadon merupakan obat sakit kepala keluarga yang juga dapat mengurangi nyeri otot, nyeri saraf dan nyeri gigi.</p>\r\n\r\n<p>Beli Oskadon tablet di apotek online K24klik sekarang dan dapatkan manfaatnya</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Sakit kepala, migrain, nyeri otot dan nyeri sendi, nyeri saraf, sakit gigi dan demam yang berhubungan dengan flu dan masuk angin</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Analgesik (Non Opiat) dan Antipiretik</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Paracetamol 500 mg, caffein 35 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dewasa : 3-4 x sehari 1-2 tablet Anak-anak : 3-4 x sehari 1/2-1 tablet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Berikan dengan atau tanpa makanan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Gangguan fungsi ginjal dan hati, hindari penggunaan bersama dengan antikoagulan oral</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Gangguan saluran pencernaan, takhikardia</p>\r\n'),
(33, 'NEOZEP F TAB 4S STRIP', 'Neozep', 3000, 525, 'mg', 'strip', 'Obat demam', '<p>Neozep Forte merupakan obat untuk meringankan gejala flu seperti demam, sakit kepala, hidung tersumbat dan bersin-bersin.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Setiap 1 tablet Neozep mengandung:</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ol>\r\n	<li>Paracetamol (Acetaminophen) adalah zat aktif yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bisa diperoleh tanpa resep dokter.</li>\r\n	<li>Dexchlorpheniramine maleate (CTM) adalah zat aktif yang digunakan untuk mengobati&nbsp; gejala alergi seperti rhinitis dan urtikaria. Termasuk dalam golongan antihistamin generasi pertama yang memiliki efek sedatif rendah.</li>\r\n	<li>Salisilamida adalah obat turunan asam salisilat yang berperan sebagai analgesik (penghilang rasa nyeri) ringan. Biasanya dalam penggunaan sering dikombinasikan dengan parasetamol dan kafein.</li>\r\n	<li>Phenylpropalamine adalah zat aktif yang berfungsi sebagai stimulan dan nasal dekongestan (untuk mengatasi pilek dan hidung tersumbat).</li>\r\n</ol>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>meringankan gejala flu seperti demam,sakit kepala, hidung tersumbat dan bersin-bersin</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Batuk dan Pilek</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>fenilpropanolamin hcl 15 mg, ctm 2mg, paracetamol 250mg, salisilamida 150 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>dewasa : 3-4 kali sehari 1 tablet. anak-6-12 thn : 3-4 kali sehari 1/2 tablet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>sesudah makan</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>penderita dengan gangguan jantung dan diabetes melitus , penderita dengan gangguan fungsi hati yang berat</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>mengantuk, gangguan pencernaan , takikardia, aritmia, mulut kering , retensi urin, iritasi lambung, penggunaan dengan dosis besar dan jangka panjang menyebapkan kerusakan hati.</p>\r\n'),
(34, 'NEO ULTRASILINE CR 5G', 'Neo Ultrasilin', 10000, 5, 'gr', 'Tube', 'Obat Bebas Terbatas', '<p>NEO ULTRASILINE CR 5G merupakan salep kulit yang dapat digunakan untuk pengobatan topikal dari candidiasis, Pityriasis versicolor, Tinea pedis, Tinea cruris dan tinea corporis. Tersedia dalam bentuk tube yang didistribusikan oleh Henson Farma.<br />\r\nBeli NEO ULTRASILINE CR 5G di K24Klik.com dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Untuk pengobatan topikal dari candidiasis, Pityriasis versicolor, Tinea pedis, Tinea cruris dan tinea corporis.</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antijamur dan Antiparasit Topikal</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Clotrimazole 1%</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>2-3 kali sehari</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Topikal, cuci bersih pada bagian kulit sebelum dioleskan krim.</p>\r\n'),
(35, 'SANGOBION CAP 10S', 'Sangobion', 16000, 350, 'mg', 'strip', 'Obat bebas', '<p>SANGOBION CAP 10&#39;S adalah vitamin &amp; zat besi penambah darah untuk mengatasi anemia (kurang darah) karena kekurangan zat besi dan mineral. Produk ini mengandung zat besi, vitamin dan mineral yang penting dalam pembentukan sel darah merah, terutama Hemoglobin (Hb) yang berperan mengangkut oksigen ke seluruh tubuh sehingga dapat membantu pembentukan sel darah merah untuk mengatasi anemia (kurang darah). Sangobion juga mengandung Vit.C yang dapat membantu meningkatkan penyerapan zat besi dan merupakan suplemen zat besi pertama yang mendapat sertifikasi halal dari MUI<br />\r\nBeli SANGOBION CAP 10&#39;S di K24Klik.com dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>anemia karena kekurangan zat besi dan mineral lain yang membantu pembentukan darah</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Vitamin dan Mineral (untuk Masa Hamil dan Nifas)/Antianemia</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>1 kapsul mengandung Ferrous Gluconate 250 mg Manganese Sulfate 0, 2 mg Copper Sulfate 0, 2 mg Vitamin C 50, 0 mg Asam Folat / Folic Acid 1,0 mg Vitamin B 12 7, 5 mcg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>1 kapsul sehari pada waktu atau sesudah makan. Dapat dikonsumsi mulai dari 3 hari sebelum dan selama periode menstruasi</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Dapat dikonsumsi mulai dari 3 hari sebelum dan selama periode menstruasi</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>akumulasi zat besi, gangguan penggunaan zat besi</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>nyeri lambung, muntah, konstipasi, diare, kolik</p>\r\n'),
(36, 'PROMAG TABLET', 'Promag', 8000, 400, 'mg', 'strip', 'Obat bebas', '<p>Promag merupakan obat kombinasi antara antasida dengan simetikon yang digunakan untuk terapi dyspepsia (maag) dengan mengurangi gejala maag seperti kembung, mual, dan bersendawa. Promag mengandung antasida Magnesium (Mg(OH)) dan Hydrotalcite dengan Simetikon yang dapat menetralkan asam lambung dan mengurangi gas yang berlebihan di saluran pencernaan (antiflatulen).</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>untuk meringankan gejala yang berhubungan dengan kelebihan asam lambung, gastritis, tukak lambung, tukak usus 12 jari, dengan gejala seperti: mual, nyeri lambung, nyeri ulu hati, kembung dan perasaan penuh pada lambung</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antasid, Obat Antirefluks &amp; Antiulserasi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>hydrotalcite 200mg, magnesium hydroxide 150 mg, simethicone 50mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>dewasa : 3-4 x sehari 1-2 tablet. Anak-anak 6-12 th : 3-4 x sehari 1/2-1 tablet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>dianjurkan untuk meminum obat ini segera pada saat timbul gejala dan dilanjutkan 1-2 jam sebelum makan atau sesudah makan dan sebelum tidur</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan di tempat sejuk dan kering, terhindar dari sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>gangguan fungsi ginjal, tidak dianjurkan untuk anak dibawah 6 tahun, tidak dianjurkan untuk digunakan terus menerus selama 2 minggu, kecuali atas &nbsp;petunjuk dokter</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>sembelit, diare, mual,muntah.</p>\r\n'),
(37, 'PROMAG CAIR 7ML', 'Promag', 15000, 7, 'ml', 'piece', 'Obat bebas', '<p>Promag cair untuk mengurangi gejala yang berhubungan dengan kelebihan asam lambung, gastritis, tukak lambung, dan tukak usus 12 jari.<br />\r\n<br />\r\n<br />\r\nBeli Promag Cair 7ML Sach 6S di K24klik dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Untuk mengurangi gejala yang berhubungan dengan kelebihan asam lambung, gastritis, tukak lambung, dan tukak usus 12 jari dengan gejala mual, kembung, nyeri lambung, nyeri ulu hati, dan rasa penuh pada lambung</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antasid, Obat Antirefluks &amp; Antiulserasi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Hydrotalcite 200mg, Mg(OH)2 150mg, Simethicone 50mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dewasa : 3-4 x sehari 1-2 sachet, anak 6-12 tahun : 1/2-1 sachet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>satu jam sebelum atau sesudah makan, dan sebelum tidur malam</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat yang sejuk dan kering, serta terlindung dari panas dan sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Aman dikonsumsi untuk ibu hamil dan menyusui</p>\r\n'),
(38, 'PROMAG GAZERO', 'Promag', 15000, 10, 'ml', 'piece', 'Obat bebas', '<p>Promag Gazero memiliki kandungan delapan (8) macam herbal yang berkhasiat dalam membantu meredakan perut kembung, mual, begah, dan masuk angin. Diformulasikan khusus dari ekstrak herbal alami jahe merah, adas, kunyit, peppermint, ananas, madu, dan royal jelly.</p>\r\n\r\n<p>Royal Jelly adalah sekresi susu yang dihasilkan oleh kelenjar lebah madu pekerja yang mengandung protein, beberapa jenis vitamin, gula, garam dan asam amino yang dipercaya bermanfaat bagi kesehatan manusia.&nbsp;</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>mengatasi perut kembung dan begah.</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antasid, Obat Antirefluks &amp; Antiulserasi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Jahe merah 50mg, adas 10mg, peppermint 12.5mg, akar manis 300mg, kunyit 50mg, ananas 50mg, royal jelly 10mg, honey 1g</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>3 x sehari 1 sachet</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>bisa diminum langsung atau dicampur dengan air hangat</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat yang kering dan terlindung dari cahaya</p>\r\n'),
(39, 'AMLODIPINE DEXA 10MG', 'Generik', 3000, 10, 'mg', 'strip', 'Obat Keras', '<p>AMLODIPINE DEXA 10MG TAB 100S termasuk obat golongan antagonis kalsium yang bekerja dengan menghambat arus masuk ion kalsium di dalam membran sel aktif. Amlodipine mampu melemaskan dinding pembuluh darah sehingga memperlancar aliran darah menuju jantung dan mengurangi tekanan darah. Amlodipine Dexa 10 mg digunakan untuk mengatasi hipertensi atau tekanan darah tinggi, terapi lini pertama untuk infark miokard serta terapi kombinasi atau monoterapi untuk angina. Obat ini dapat dikonsumsi sebelum atau sesudah makan dengan air putih dengan memastikan ada jarak yang cukup antara satu dosis dengan dosis berikutnya.Tidak disarankan penggunaan pada pasien dengan riwayat hipersensitif terhadap dihidropiridin. Interaksi dapat terjadi apabila digunakan bersamaan dengan obat-obatan seperti: *Amiodarone *Simvastatin *Clarithromycin *Clopidogrel *Ciclosporin *Dantrolene *Digoxin Beli AMLODIPINE DEXA 10MG TAB 100S di K24Klik dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Hipertensi, infark miokard, angina</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antagonis Kalsium</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Amlodipine 10 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dapat diberikan sebelum atau sesudah makan.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>*Hipertensi &amp; angina: Awal 5 mg/hari dapat ditingkatkan menjadi 10 mg/hari. *Angina stabil kronik atau angina vasospatik 5-10 mg.</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan di tempat sejuk dan kering, serta terhindar dari sinar matahari langsung.</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>*Gangguan hati dan ginjal *Gagal jantung kongestif *Hamil dan laktasi *Anak *Lanjut usia</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Sakit kepala, edema, lelah, somnolen, mual, nyeri perut, rasa hangat dan kemerahan pada wajah, palpitasi dan pusing.</p>\r\n'),
(40, 'BIOPLACENTON GEL 15G', 'Bioplacenton', 30000, 15, 'gr', 'Tube', 'Obat Keras', '<p>BIOPLACENTON GEL 15G merupakan obat yang memiliki kandungan Placenta Extract dan Neomycin Sulfate. Obat ini digunakan untuk mengobati luka bakar, luka dengan infeksi, serta luka kronik dan jenis luka yang lain.&nbsp;</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>penyembuhan luka bakar, luka terinfeksi, scald, dan ulkus kulit</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antibiotik Topikal</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>ekstrak placenta dari sapi 10%, neomycin sulfate 0.5%, jelly base</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>3-5 kali sehari, dioleskan</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>dioleskan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>hipersensitif terhadap komponen</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>reaksi hipersensitif, ototoksisitas jika bersamaan jika diberikan bersamaan obat ototoksik lainnya</p>\r\n'),
(41, 'DEXAMETHASONE KF 0.5MG', 'Generik', 3000, 5, 'mg', 'strip', 'Obat Keras', '<p>Dexamethason produksi PT. Kimia Farma telah terdaftar pada BPOM. Pada setiap tabletnya mengandung 0,5mg dexamethasone. Dexamethasone merupakan glukokortikoid sintetis yang bekerja mengurangi peradangan dengan menghambat migrasi leukosit dan pembalikan permeabilitas kapiler yang meningkat. Dexamethason efektif digunakan untuk terapi terhadap inflamasi, alergi dan penyakit lain yang responsif terhadap glukokortikoid.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>inflamasi, alergi dan penyakit lain yang responsif terhadap glukokortikoid</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Hormon Kortikosteroid</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>dexamethasone 0,5mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>0,5-10mg per hari</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>diminum saat makan</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>hipotiroid, sirosis hati, terapi jangka lama</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>lemah otot, osteoporosis, tukak peptik, gangguan penyembuhan luka, keringat berlebih, sakit kepala, gangguan siklus haid, hambat pertumbuhan pada anak, penurunan toleransi terhadap karbohidrat</p>\r\n'),
(42, 'GENTAMICYN SULFAT 5G', 'Generik', 5000, 5, 'gr', 'Tube', 'Obat Keras', '<p>Salep Garamycin mengandung antibiotik gentamicin yang merupakan antibiotik golongan aminoglikosida, yang mempunyai efek bakterisidal terutama terhadap basilus aerobik gram negatif yang sensitif, dan bakteri gram positif yang sensitif.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Untuk pengobatan topikal infeksi primer dan sekunder pada kulit yang disebabkan oleh bakteri yang peka terhadap gentamicin. Tidak digunakan untuk antibiotik pencegahan/profilaksis karena bakteri penyebab tidak diketahui</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antibiotik Topikal</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Setiap 1 gram Garamycin mengandung gentamicin sulfate yang ekuivalen dengan 1 mg (0,1%) Gentamicin.</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Krim/Salep Garamisin dioleskan tipis pada daerah yang sakit sebanyak 3 &ndash; 4 kali sehari sampai tercapai kesembuhan. Daerah yang sakit boleh ditutupi dengan perban (gauze dressing).</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Tidak boleh digunakan untuk pengobatan mata</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Penggunaan topikal antibiotik gentamisin dapat menyebabkan iritasi yang bersifat sementara, biasanya ditandai dengan kulit kemerahan dan gatal. Kemungkinan terjadinya fotosensitisasi pernah dilaporkan pada beberapa pasien. Penggunaan antibiotik gentamisin topikal dalam jangka panjang dapat menyebabkan jamur atau bakteri yang kebal tumbuh berlebihan.</p>\r\n'),
(43, 'PIROXICAM IF 20MG ', 'Generik', 3000, 20, 'mg', 'strip', 'Obat Keras', '<p>Piroxicam merupakan obat generik yang diproduksi oleh PT Indofarma. Piroxicam termasuk golongan NSAID yang sangat berisiko bila digunakan oleh pasien yang sudah memiliki masalah jantung sebelumnya. Piroxicam digunakan untuk mengobati rheumatoid arthritis dan osteoarthritis. Cara kerja Piroxicam yaitu dengan mengurangi hormon yang menyebabkan peradangan dan rasa nyeri di tubuh</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Osteoarthritis, spondilitis ankilosa, gangguan muskuloskeletal akut, gout akut,</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Anti Inflamasi Non Steroid (OAINS)</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Piroxicam 20 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>reumatoid arthritis, osteoarthritis, spondilitis ankilosa : 1 x sehari 20 mg ; Gangguan muskoloskeletal akut : 40 mg/hari dalam dosis tunggal atau terbagi selama 2 hari, kemudian 1 x sehari 20 mg selama 7-14 hari ; Gout akut : dosis awal 40 mg /hari dalam dosis tunggal, kemudian 40 mg dosis tunggal atau terbagi selama 4-6 hari. Tidak untuk terapi gout jangka panjang</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Diberikan sesudah makan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Riwayat ulkus gaster, gangguan jantung, hipertensi, kerusakan ginjal atau hati, retensi urine, usia lanjut</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Gangguan pencernaan, sakit kepala, pusing, penglihatan kabur, iritasi</p>\r\n'),
(44, 'RANITIDINE HEXPHARM 150MG', 'HEXPHARM', 4000, 150, 'mg', 'strip', 'Obat Keras', '<p>Ranitidine Hexpharm merupakan obat antasida yang diproduksi oleh PT. Hexpharm dan telah terdaftar pada BPOM. Ranitidine Hexpharm mengandung 150mg ranitidine pada setiap tabletnya. Ranitidine Hexpharm dapat digunakan untuk mengobati tukak duodenum aktif jangka pendek, tukak lambung aktif dan menurangi gejala refluks esofagitis. Ranitidine Hexpharm juga dapat digunakan untuk terapi pemeliharaan setelah penyembuhan tukak duodenum dan lambung.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>pengobatan jangka pendek tukak dudenum aktif, tukak lambung aktif, mengurangi gejala refluks esofagitis, terapi pemeilharan setelah penyembuhan tukak duodenum dan lambung.</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antasid, Obat Antirefluks &amp; Antiulserasi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>ranitidine 150mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>tukak duodenum : 2 kali sehari 150mg (pagi dan malam) selama 4-8minggu. tukak lambung aktif : 2 kali sehari 150mg (pagi dan malam) selama 2 minggu. terapi pemeliharaan tukak duodenum dan lambung : 1 kali sehari 150mg sebelum tidur. refluks gastro esofagitis : 2 kali sehari 150mg. esofagitis erosif : 4 kali sehari 150mg. terapi pemeliharaan esofagitis erosif : 2 kali sehari 150mg.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>diminum sebelum atau setelah makan</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>pasien dengan riwayat profiria akut. ibu hamil dan menyusui, anak, usia lanjut. gangguan fungsi hati dan ginjal.</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>sakit kepala, malaise (merasa lemas dan kurang fit), pusing, mengantuk, insomnia, vertigo, agitasi (resah dan gelisah), depresi, halusinasi, gangguan gastrointestinal.</p>\r\n'),
(45, 'RANITIDINE 150MG', 'Generik', 3000, 150, 'mg', 'strip', 'Obat Keras', '<p>Ranitidine yang diproduksi oleh Erela merupakan penghambat histamin, yang bekerja dengan memblokir histamin yang merangsang pelepasan asam lambung. Oleh karena itu, Ranitidine dapat digunakan untuk mengobati ulkus duodenum aktif, ulkus gaster benigna aktif, refluks esofagitis, pencegahan relaps ulkus peptikum, hipersekresi patologis seperti sindroma zollinger-ellison. Ranitidine diproduksi dalam bentuk tablet selaput untuk menutupi rasa pahit dari zat aktif yang terdapat di dalamnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>ulkus duodenum aktif, ulkus gaster benigna aktif, refluks esofagitis, pencegahan relaps ulkus peptikum, hipersekresi patologis</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antasid, Obat Antirefluks &amp; Antiulserasi</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Ranitidine HCl</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>tukak duodenum aktif dan ulkus gaster benigna: 2 kali sehari 150 mg selama 4-8 mg, pemeliharaan 1 kali sehari 150 mg sebelum tidur malam. Refluks esofagitis: 2 kali sehari 150 mg selama kurang dari sama dengan 8 minggu. Pencegahan relaps ulkus peptikum 150 mg menjelang tidur untuk 12 bulan. Kondisi hipersekresi patologis: awal 3 kali sehari 150 mg dan dapat ditingkatkan menjadi kurang dari sama dengan 6 gram per hari dalam dosis terbagi. Pasien dengan gangguan ginjal dengan bersihan kreatinin &lt; 50ml/menit 150 mg/24jam.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>diminum sebelum atau sesudah makan dan sebelum tidur malam</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung</p>\r\n'),
(46, 'SCABIMITE CR 10G', 'Scabimite', 65000, 10, 'gr', 'Tube', 'Obat Keras', '<p>Scabimite merupakan obat berbentuk krim yang mengandung 5% permethrin.Scabimite diproduksi oleh PT. Galenium Pharmasia Lab-Indonesia dan telah terdaftar pada BPOM. Scabimite dapat digunakan untuk mengobati masalah kulit yaitu skabies (gatal pada kulit yang disebabkan oleh tungau atau kutu kecil).</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>skabies</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Antijamur dan Antiparasit Topikal</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>permethrin 5%</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>oleskan 1 kali sehari</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>oleskan pada bagian yang gatal di malam hari</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>hindari kontak dengan mata. ibu hamil dan menyusui. bayi</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>rasa terbakar dan tersengat yang ringan dan sementara,gatal, eritema, ruam kulit</p>\r\n');
INSERT INTO `listproduk` (`id_produk`, `nama`, `merk`, `harga`, `ukuran`, `satuan_ukuran`, `satuan_barang`, `jenis`, `deskripsi`) VALUES
(47, 'SIMVASTATIN KF 10MG', 'Generik', 3000, 10, 'mg', 'strip', 'Obat Keras', '<p>Obat Simvastatin banyak diproduksi oleh perusahaan-perusahaan farmasi di Indonesia, salah satunya adalah Kimia Farma dengan potensi 20 mg. Simvastatin termasuk dalam golongan obat inhibitor reductase HMG CoA atau statin. Simvastatin mengurangi kadar kolesterol buruk (LDL) dan trigliserid dalam darah, sekaligus menaikkan kadar HDL (kolesterol baik). Selain itu, Simvastatin juga digunakan untuk menurunkan risiko stroke, serangan jantung, dan komplikasi jantung lainnya pada penderita diabetes, penyakit jantung koroner, atau faktor risiko yang lain. Simvastatin hanya digunakan oleh orang dewasa dan anak-anak paling tidak usia 10 tahun</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Mengurangi kadar kolesterol total dan ldl pada penderita hiperkolesterolemia primer dan sekunder , meningkatkan kadar hdl</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Dislipidemia</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Simvastatin 10 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>awal : 1 x 10 mg sehari sebagai anti hiperkolesterol ringan 5 mg sehari maksimal 40 mg sehari</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Malam hari sebelum tidur</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>Jangan mengkonsumsi jus grapefruit secara berlebihan. Monitoring kadar lipid tiap 3 bulan (pada pemakaian lama). gangguan hepatik akut, peningkatan sgot/sgpt tanpa penjelasan, hamil dan laktasi</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>nyeri abdomen, konstipasi, dan kembung</p>\r\n'),
(48, 'SIMVASTATIN HEXPHARM 10MG', 'HEXPHARM', 4000, 10, 'mg', 'strip', 'Obat Keras', '<p>SIMVASTATIN HEXPHARM 10MG TAB 100S merupakan obat untuk mengurangi kadar kolesterol buruk (LDL) dan trigliserid dalam darah, sekaligus menaikkan kadar HDL (kolesterol baik) serta digunakan untuk menurunkan risiko kematian karena penyakit jantung koroner, menurunkan risiko infark miokard non fatal, menurunkan risiko pada pasien yang sedang menjalani tindakan revaskularisasi miokardial. Simvastatin termasuk obat golongan inhibitor reductase HMG CoA atau statin yang bekerja dengan cara menghambat enzim pembentuk kolesterol jahat sehingga kadar kolesterol dalam darah berkurang. Simvastatin dapat dikonsumsi sebelum atau sesudah makan pada malam hari, biasanya satu kali setiap hari di waktu malam sebelum tidur atau sesuai yang disarankan oleh dokter. Konsultasikan kepada dokter terlebih dahulu apabila akan digunakan pada pasien dengan kondisi alergi terhadap makanan atau kandungan yang terdapat pada obat ini, pasien dengan penyakit hati aktif atau peningkatan persisten transaminase serum, wanita hamil dan menyusui serta pasien dengan penyakit ginjal dan penyakit tiroid. Interaksi dapat terjadi apabila digunakan bersamaan dengan obat-obatan seperti: *Imunosupresan *Itrakonazol *Gemfibrozil *Niasin *Eritromisin *Kumarin *Antipirin *Propanolol *Digoksin Interaksi simvastatin dan makanan dapat terjadi terutama dengan grapefruit (limau gedang). Buah ini dapat meningkatkan penyerapan obat dalam aliran darah. Beli SIMVASTATIN HEXPHARM 10MG TAB 100S di K24Klik dan dapatkan manfaatnya.</p>\r\n\r\n<h2>Indikasi / Manfaat / Kegunaan :</h2>\r\n\r\n<p>Menurunkan kadar kolestrol total &amp; LDL pada pasien dengan hiperkolesterolemia primer (tipe IIa &amp; IIb).</p>\r\n\r\n<h2>Sub Kategori</h2>\r\n\r\n<p>Obat Dislipidemia</p>\r\n\r\n<h2>Komposisi</h2>\r\n\r\n<p>Simvastatin 10 mg</p>\r\n\r\n<h2>Dosis</h2>\r\n\r\n<p>Dapat diberikan sebelum atau sesudah makan pada malam hari.</p>\r\n\r\n<h2>Penyajian</h2>\r\n\r\n<p>Awal: 5-10 mg 1 kali sehari (malam hari). Maksimal 40 mg/hari sebagai dosis tunggal.</p>\r\n\r\n<h2>Cara Penyimpanan</h2>\r\n\r\n<p>Simpan di tempat sejuk dan kering, serta terhindar dari sinar matahari langsung.</p>\r\n\r\n<h2>Perhatian</h2>\r\n\r\n<p>*Pantau kadar kolesterol secara periodik selama terapi. Lakukan tes fungsi hati sebelum terapi, 6 &amp; 12 bulan setelah terapi pertam dan selanjutnya secara periodik. *Riwayat penyakit hati. *Miopati akut dan berat atau pasien dengan risiko gagal ginjal sekunder akibat rabdomiolisis.</p>\r\n\r\n<h2>Efek Samping</h2>\r\n\r\n<p>Nyeri perut, konstipasi, kembung, astenia, sakit kepala, miopati, rabdomiolisis, tremor, pusing, vertigo.</p>\r\n'),
(49, 'Sabun Bengkoang', 'Tazakka', 7000, 90, 'gr', 'kotak', 'Obat herbal', '<p>Sabun Herbal dari Tazakka dengan ekstrak Bengkoang sangat cocok untuk mencerahkan kulitmu.</p>\r\n'),
(50, 'Sabun Madu', 'Tazakka', 7000, 90, 'gr', 'kotak', 'Obat herbal', '<p>Sabun herbal Tazakka dengan ekstrak madu propolis cocok untuk membuat kulitmu lebih lembab.</p>\r\n'),
(51, 'Sabun Sirih', 'Tazakka', 7000, 90, 'gr', 'kotak', 'Obat herbal', '<p>Sabun herbal Tazakka dengan ekstrak sirih cocok untuk membuat kulitmu kencang.</p>\r\n'),
(52, 'Sabun Susu', 'Tazakka', 7000, 90, 'gr', 'kotak', 'Obat herbal', '<p>Sabun herbal Tazakka mengandung susu ini cocok untuk merawat kesehatan kulitmu.</p>\r\n'),
(53, 'Sabun Zaitun', 'Tazakka', 7000, 90, 'gr', 'kotak', 'Obat herbal', '<p>Sabun herbal Tazakka dengan kandungan Zaitun ini cocok untuk membuat kulitmu menjadi lebih lembab.</p>\r\n'),
(54, 'Madu Anak', 'Ratu Lebah', 18500, 150, 'gr', 'Botol', 'Obat herbal', '<p>Madu dari Ratu Lebah untuk memperbaiki nafsu makan dan meningkatkan daya tahan tubuh anak.</p>\r\n'),
(55, 'Madu Hitam', 'Ratu Lebah', 46000, 470, 'gr', 'Botol', 'Obat herbal', '<p>Madu Hitam dari Ratu Lebah cocok untuk meningkatkan daya tahan tubuh.</p>\r\n'),
(56, 'Gold - G Bio Sea Cucumber', 'Gamat Gold', 35000, 100, 'ml', 'Botol', 'Obat herbal', ''),
(57, 'Madu Hitam Pahit', 'Gamat Gold', 55500, 470, 'ml', 'Botol', 'Obat herbal', ''),
(58, 'Cussons Baby Almond & Rose Oil', 'Cussons Baby', 17000, 100, 'ml', 'Botol', 'Anak', ''),
(59, 'Cussons Baby Powder 2 + 1', 'Cussons Baby', 15000, 100, 'gr', 'Botol', 'Anak', ''),
(60, 'Cussons Baby Tisu Basah 1 + 1', 'Cussons Baby', 17000, 50, 'sheets', 'kotak', 'Anak', ''),
(61, 'Dodo SA1', 'Dodo', 14000, 1, 'gr', 'piece', 'Anak', ''),
(62, 'Dodo 106N', 'Dodo', 8500, 1, 'gr', 'piece', 'Anak', ''),
(63, 'Johnsons Baby Oil', 'Johnsons', 20000, 125, 'ml', 'Botol', 'Anak', ''),
(64, 'Lactacyd Baby', 'Lactacyd', 25500, 60, 'ml', 'Botol', 'Anak', ''),
(65, 'Telon Lang Minyak Telon', 'Telon Lang', 36000, 150, 'ml', 'Botol', 'Anak', ''),
(66, 'Mami Breast Pump', 'Mami', 12000, 1, 'gr', 'piece', 'Anak', ''),
(67, 'Mamy Love Wipes', 'Mamy', 16000, 50, 'sheets', 'kotak', 'Anak', ''),
(68, 'Marcks Bedak', 'Marcks', 16000, 1, 'gr', 'piece', 'Kecantikan', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `listproduk`
--
ALTER TABLE `listproduk`
  ADD PRIMARY KEY (`id_produk`);
SET FOREIGN_KEY_CHECKS=0;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
